import { AppMeta, Content } from "newt-client-js";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Cover } from "../components/Cover";
import { Layout } from "../components/Layout";
import { Dropdown } from "../components/Dropdown";
import { Category } from "../types/category";
import { ArticleCard } from "../components/ArticleCard";
import { Article } from "../types/article";
import { Pagination } from "../components/Pagination";

export function Home({
  app,
  categories,
  articles,
  total,
}: {
  app: AppMeta;
  categories: (Content & Category)[];
  articles: (Content & Article)[];
  total: number;
}) {
  return (
    <Layout app={app}>
      <Head>
        <title>{app?.name || app?.uid || ""}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {app.cover?.value && <Cover app={app} />}
      <div className={styles.Articles}>
        <Dropdown categories={categories} />
        <div className={styles.Inner}>
          {articles.map((article) => (
            <ArticleCard article={article} key={article._id} />
          ))}
        </div>
        <Pagination total={total} current={1} />
      </div>
    </Layout>
  );
}
